package tech.tyman.plugins.translate

import com.discord.api.commands.CommandChoice

open class TranslateData

data class TranslateSuccessData(
    val sourceLanguage: String,
    val translatedLanguage: String,
    val sourceText: String,
    val translatedText: String
) : TranslateData()

data class TranslateErrorData(
    val errorCode: Number,
    val errorText: String
) : TranslateData()

val languageCodes = mapOf(
    "Afrikaans" to "af",
    "Albanian" to "sq",
    "Amharic" to "am",
    "Arabic" to "ar",
    "Armenian" to "hy",
    "Assamese" to "as",
    "Azerbaijani" to "az",
    "Bangla" to "bn",
    "Basque" to "eu",
    "Belarusian" to "be",
    "Bosnian" to "bs",
    "Bulgarian" to "bg",
    "Burmese" to "my",
    "Cantonese" to "zh-yue",
    "Catalan" to "ca",
    "Cebuano" to "ceb",
    "Central Kurdish" to "ckb",
    "Chakma" to "ccp",
    "Cherokee" to "chr",
    "Chinese (Hong Kong)" to "zh-HK",
    "Chinese (Simplified, China)" to "zh-Hans",
    "Chinese (Simplified)" to "zh-CN",
    "Chinese (Traditional, Taiwan)" to "zh-Hant",
    "Chinese (Traditional)" to "zh-TW",
    "Corsican" to "co",
    "Croatian" to "hr",
    "Czech" to "cs",
    "Danish" to "da",
    "Dutch" to "nl",
    "Dzongkha" to "dz",
    "English" to "en",
    "Esperanto" to "eo",
    "Estonian" to "et",
    "Filipino" to "fil",
    "Filipino" to "tl",
    "Finnish" to "fi",
    "French" to "fr",
    "Fulah" to "ff",
    "Galician" to "gl",
    "Georgian" to "ka",
    "German" to "de",
    "Greek" to "el",
    "Gujarati" to "gu",
    "Haitian Creole" to "ht",
    "Hawaiian" to "haw",
    "Hebrew" to "he",
    "Hindi" to "hi",
    "Hmong" to "hmn",
    "Hungarian" to "hu",
    "Icelandic" to "is",
    "Indonesian" to "id",
    "Inuktitut" to "iu",
    "Irish" to "ga",
    "Italian" to "it",
    "Japanese" to "ja",
    "Javanese" to "jv",
    "Javanese" to "jw",
    "Kannada" to "kn",
    "Kazakh" to "kk",
    "Khmer" to "km",
    "Korean" to "ko",
    "Kurdish" to "ku",
    "Kyrgyz" to "ky",
    "Lao" to "lo",
    "Latin" to "la",
    "Latvian" to "lv",
    "Lisu" to "lis",
    "Lithuanian" to "lt",
    "Luxembourgish" to "lb",
    "Macedonian" to "mk",
    "Makah" to "myh",
    "Malagasy" to "mg",
    "Malay" to "ms",
    "Malayalam" to "ml",
    "Maltese" to "mt",
    "Manipuri (Meitei Mayek)" to "mni-Mtei",
    "Maori" to "mi",
    "Marathi" to "mr",
    "Menominee" to "mez",
    "Mongolian" to "mn",
    "Navajo" to "nv",
    "Nepali" to "ne",
    "Norwegian Nynorsk" to "nn",
    "Norwegian" to "nb",
    "Norwegian" to "no",
    "Nyanja" to "ny",
    "Odia" to "or",
    "Ojibwa" to "oj",
    "Oneida" to "one",
    "Osage" to "osa",
    "Pashto" to "ps",
    "Persian" to "fa",
    "Plains Cree" to "crk",
    "Polish" to "pl",
    "Portuguese (Brazil)" to "pt-BR",
    "Portuguese (Portugal)" to "pt-PT",
    "Punjabi" to "pa",
    "Rohingya" to "rhg",
    "Romanian" to "ro",
    "Romany" to "rom",
    "Russian" to "ru",
    "Samoan" to "sm",
    "Sanskrit" to "sa",
    "Scottish Gaelic" to "gd",
    "Seneca" to "see",
    "Serbian" to "sr",
    "Shona" to "sn",
    "Sindhi" to "sd",
    "Sinhala" to "si",
    "Slovak" to "sk",
    "Slovenian" to "sl",
    "Somali" to "so",
    "Southern Uzbek" to "uzs",
    "Spanish" to "es",
    "Sundanese" to "su",
    "Swahili" to "sw",
    "Swedish" to "sv",
    "Tajik" to "tg",
    "Tamil" to "ta",
    "Tatar" to "tt",
    "Telugu" to "te",
    "Thai" to "th",
    "Tibetan" to "bo",
    "Tigrinya" to "ti",
    "Turkish" to "tr",
    "Ukrainian" to "uk",
    "Urdu" to "ur",
    "Uyghur" to "ug",
    "Uzbek" to "uz",
    "Vietnamese" to "vi",
    "Welsh" to "cy",
    "Western Frisian" to "fy",
    "Xhosa" to "xh",
    "Yiddish" to "yi",
    "Yoruba" to "yo",
    "Zulu" to "zu"
)

val languageCodeChoices = languageCodes.map {CommandChoice(it.key, it.value)}